export type CocoaVariety = 'Nacional' | 'Ccn51' | 'Trinitario' | 'Otro';
export type CocoaState = 'Baba' | 'Seco';
export type PaymentMethod = 'Efectivo' | 'Transferencia' | 'Cheque' | 'Otro';
export type PublicContentSection = 'Hero' | 'Nosotros' | 'Contacto' | 'Servicio' | 'Beneficio' | 'Proceso' | 'Impacto' | 'Testimonio' | 'Galeria' | 'Footer' | 'CarruselNosotros';
export type CashRegisterStatus = 'Abierta' | 'Cerrada';
export type CashMovementDirection = 'Ingreso' | 'Egreso';
export type CashMovementCategory = 'CompraCacao' | 'VentaCacao' | 'GastoOperativo' | 'Aporte' | 'Retiro' | 'Ajuste';
export type ProcessingStatus = 'EnProceso' | 'Completado' | 'Cancelado';
export type InventoryLotStatus = 'Disponible' | 'Agotado' | 'EnProceso' | 'Anulado';

export interface PublicPrice { businessName: string; logoUrl: string; priceClockLabel: string; timeZone: string; dryPricePerQuintal: number; wetPricePerQuintal: number; marketPricePerMetricTon: number; updatedAtUtc: string; source: string; isManual: boolean; contactWhatsApp: string; contactAddress: string; contactPhone: string; contactEmail: string; googleMapsEmbedUrl: string; location: string; pickupEnabled: boolean; nextAutomaticRefreshAtUtc: string; }
export interface Producer { id: string; fullName: string; documentNumber: string; farmLocation: string; phone: string; email?: string; preferredPaymentMethod: PaymentMethod; notes?: string; isActive: boolean; purchaseCount: number; totalQuintals: number; totalPaid: number; createdAtUtc: string; }
export interface Purchase { id: string; code: string; producerId: string; producerName: string; producerEmail?: string; variety: CocoaVariety; state: CocoaState; grossWeightLbs: number; tareLbs: number; humidityPercent: number; shrinkagePercent: number; netWeightLbs: number; payableQuintals: number; unitPrice: number; totalPaid: number; paymentMethod: PaymentMethod; purchasedAtUtc: string; notes?: string; isVoided: boolean; }
export interface Sale { id: string; code: string; customerName: string; customerTaxId?: string; customerEmail?: string; variety: CocoaVariety; state: CocoaState; quantityQuintals: number; unitPrice: number; costBasisPerQuintal: number; total: number; grossProfit: number; paymentMethod: PaymentMethod; soldAtUtc: string; notes?: string; isVoided: boolean; }
export interface InventoryItem { variety: CocoaVariety; state: CocoaState; quantityQuintals: number; averagePurchaseCost: number; estimatedValue: number; }
export interface InventoryLot { id: string; code: string; purchaseId?: string; processingBatchId?: string; variety: CocoaVariety; state: CocoaState; initialQuantityQuintals: number; availableQuantityQuintals: number; unitCost: number; humidityPercent: number; status: InventoryLotStatus; receivedAtUtc: string; notes?: string; }
export interface DashboardData { purchasesThisMonth: number; salesThisMonth: number; grossProfitThisMonth: number; inventoryQuintals: number; activeProducers: number; purchasesCountThisMonth: number; currentCashBalance?: number | null; recentPurchases: Purchase[]; inventory: InventoryItem[]; }
export interface SettingsData { businessName: string; logoUrl: string; priceClockLabel: string; timeZone: string; marginPerQuintal: number; wetPriceFactor: number; useManualPrice: boolean; manualDryPricePerQuintal?: number; currentMarketPricePerMetricTon: number; currentDryPricePerQuintal: number; currentWetPricePerQuintal: number; currentPriceUpdatedAtUtc: string; apiLastSuccessAtUtc?: string; apiLastError?: string; priceSource: string; contactWhatsApp: string; contactAddress: string; contactPhone: string; contactEmail: string; googleMapsEmbedUrl: string; location: string; pickupEnabled: boolean; emailSendingEnabled: boolean; smtpHost: string; smtpPort: number; smtpEmail: string; smtpPasswordConfigured: boolean; smtpUseSsl: boolean; }
export interface ReceiptEmailResult { sent: boolean; message: string; recipient: string; }
export interface PublicContent { id: string; contentKey: string; section: PublicContentSection; eyebrow: string; title: string; subtitle: string; body: string; primaryCtaLabel?: string; primaryCtaUrl?: string; secondaryCtaLabel?: string; secondaryCtaUrl?: string; icon?: string; imageUrl?: string; displayOrder: number; isPublished: boolean; updatedAtUtc: string; }
export interface CashMovement { id: string; direction: CashMovementDirection; category: CashMovementCategory; amount: number; description: string; referenceId?: string; referenceCode?: string; paymentMethod: PaymentMethod; occurredAtUtc: string; }
export interface CashRegister { id: string; businessDate: string; openingBalance: number; totalIncome: number; totalExpense: number; expectedBalance: number; countedClosingBalance?: number; closingDifference?: number; status: CashRegisterStatus; openedAtUtc: string; closedAtUtc?: string; notes?: string; movements: CashMovement[]; }
export interface ProcessingBatch { id: string; code: string; variety: CocoaVariety; inputWetQuintals: number; expectedDryYieldPercent: number; outputDryQuintals?: number; actualDryYieldPercent?: number; lossPercent?: number; inputUnitCost: number; outputUnitCost?: number; status: ProcessingStatus; startedAtUtc: string; completedAtUtc?: string; notes?: string; }
