CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260831014915_InitialCreate') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'cacao') THEN
            CREATE SCHEMA cacao;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260831014915_InitialCreate') THEN
    CREATE TABLE cacao."AdminUsers" (
        "Id" uuid NOT NULL,
        "FullName" text NOT NULL,
        "Email" character varying(180) NOT NULL,
        "PasswordHash" character varying(500) NOT NULL,
        "IsActive" boolean NOT NULL,
        "LastLoginAtUtc" timestamp with time zone,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_AdminUsers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260831014915_InitialCreate') THEN
    CREATE TABLE cacao."BusinessSettings" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "BusinessName" text NOT NULL,
        "MarginPerQuintal" numeric(14,2) NOT NULL,
        "WetPriceFactor" numeric(8,4) NOT NULL,
        "UseManualPrice" boolean NOT NULL,
        "ManualDryPricePerQuintal" numeric(14,2),
        "CurrentMarketPricePerMetricTon" numeric(14,2) NOT NULL,
        "CurrentDryPricePerQuintal" numeric(14,2) NOT NULL,
        "CurrentWetPricePerQuintal" numeric(14,2) NOT NULL,
        "CurrentPriceUpdatedAtUtc" timestamp with time zone NOT NULL,
        "ApiLastSuccessAtUtc" timestamp with time zone,
        "ApiLastError" text,
        "PriceSource" text NOT NULL,
        "ContactWhatsApp" text NOT NULL,
        "Location" text NOT NULL,
        "PickupEnabled" boolean NOT NULL,
        "UpdatedAtUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_BusinessSettings" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260831014915_InitialCreate') THEN
    CREATE TABLE cacao."InventoryMovements" (
        "Id" uuid NOT NULL,
        "Type" integer NOT NULL,
        "Variety" integer NOT NULL,
        "State" integer NOT NULL,
        "QuantityQuintals" numeric(14,4) NOT NULL,
        "UnitAmount" numeric(14,2) NOT NULL,
        "ReferenceId" uuid NOT NULL,
        "ReferenceCode" text NOT NULL,
        "OccurredAtUtc" timestamp with time zone NOT NULL,
        "Notes" text,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_InventoryMovements" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260831014915_InitialCreate') THEN
    CREATE TABLE cacao."PriceHistory" (
        "Id" uuid NOT NULL,
        "MarketPricePerMetricTon" numeric(14,2) NOT NULL,
        "DryPricePerQuintal" numeric(14,2) NOT NULL,
        "WetPricePerQuintal" numeric(14,2) NOT NULL,
        "MarginPerQuintal" numeric(14,2) NOT NULL,
        "Source" text NOT NULL,
        "QuotedAtUtc" timestamp with time zone NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_PriceHistory" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260831014915_InitialCreate') THEN
    CREATE TABLE cacao."Producers" (
        "Id" uuid NOT NULL,
        "FullName" character varying(160) NOT NULL,
        "DocumentNumber" character varying(20) NOT NULL,
        "FarmLocation" character varying(240) NOT NULL,
        "Phone" character varying(30) NOT NULL,
        "PreferredPaymentMethod" integer NOT NULL,
        "Notes" text,
        "IsActive" boolean NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Producers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260831014915_InitialCreate') THEN
    CREATE TABLE cacao."Sales" (
        "Id" uuid NOT NULL,
        "Code" text NOT NULL,
        "CustomerName" text NOT NULL,
        "CustomerTaxId" text,
        "Variety" integer NOT NULL,
        "State" integer NOT NULL,
        "QuantityQuintals" numeric(14,4) NOT NULL,
        "UnitPrice" numeric(14,2) NOT NULL,
        "CostBasisPerQuintal" numeric(14,2) NOT NULL,
        "Total" numeric(14,2) NOT NULL,
        "GrossProfit" numeric(14,2) NOT NULL,
        "SoldAtUtc" timestamp with time zone NOT NULL,
        "Notes" text,
        "IsVoided" boolean NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Sales" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260831014915_InitialCreate') THEN
    CREATE TABLE cacao."Purchases" (
        "Id" uuid NOT NULL,
        "Code" text NOT NULL,
        "ProducerId" uuid NOT NULL,
        "Variety" integer NOT NULL,
        "State" integer NOT NULL,
        "GrossWeightLbs" numeric(14,2) NOT NULL,
        "TareLbs" numeric(14,2) NOT NULL,
        "HumidityPercent" numeric(14,2) NOT NULL,
        "ShrinkagePercent" numeric(14,2) NOT NULL,
        "NetWeightLbs" numeric(14,2) NOT NULL,
        "PayableQuintals" numeric(14,4) NOT NULL,
        "UnitPrice" numeric(14,2) NOT NULL,
        "TotalPaid" numeric(14,2) NOT NULL,
        "PaymentMethod" integer NOT NULL,
        "PurchasedAtUtc" timestamp with time zone NOT NULL,
        "Notes" text,
        "IsVoided" boolean NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Purchases" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Purchases_Producers_ProducerId" FOREIGN KEY ("ProducerId") REFERENCES cacao."Producers" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260831014915_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_AdminUsers_Email" ON cacao."AdminUsers" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260831014915_InitialCreate') THEN
    CREATE INDEX "IX_InventoryMovements_Variety_State_OccurredAtUtc" ON cacao."InventoryMovements" ("Variety", "State", "OccurredAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260831014915_InitialCreate') THEN
    CREATE INDEX "IX_PriceHistory_QuotedAtUtc" ON cacao."PriceHistory" ("QuotedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260831014915_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Producers_DocumentNumber" ON cacao."Producers" ("DocumentNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260831014915_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Purchases_Code" ON cacao."Purchases" ("Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260831014915_InitialCreate') THEN
    CREATE INDEX "IX_Purchases_ProducerId" ON cacao."Purchases" ("ProducerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260831014915_InitialCreate') THEN
    CREATE INDEX "IX_Purchases_PurchasedAtUtc" ON cacao."Purchases" ("PurchasedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260831014915_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Sales_Code" ON cacao."Sales" ("Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260831014915_InitialCreate') THEN
    CREATE INDEX "IX_Sales_SoldAtUtc" ON cacao."Sales" ("SoldAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260831014915_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260831014915_InitialCreate', '8.0.11');
    END IF;
END $EF$;
COMMIT;
START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260831033333_BusinessCmsAndOperations') THEN
    ALTER TABLE cacao."Sales" ADD "PaymentMethod" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260831033333_BusinessCmsAndOperations') THEN
    CREATE TABLE cacao."CashRegisters" (
        "Id" uuid NOT NULL,
        "BusinessDate" date NOT NULL,
        "OpeningBalance" numeric(14,2) NOT NULL,
        "CountedClosingBalance" numeric(14,2),
        "ExpectedClosingBalance" numeric(14,2),
        "ClosingDifference" numeric(14,2),
        "Status" integer NOT NULL,
        "OpenedAtUtc" timestamp with time zone NOT NULL,
        "ClosedAtUtc" timestamp with time zone,
        "Notes" text,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_CashRegisters" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260831033333_BusinessCmsAndOperations') THEN
    CREATE TABLE cacao."ProcessingBatches" (
        "Id" uuid NOT NULL,
        "Code" text NOT NULL,
        "Variety" integer NOT NULL,
        "InputWetQuintals" numeric(14,4) NOT NULL,
        "ExpectedDryYieldPercent" numeric(14,2) NOT NULL,
        "OutputDryQuintals" numeric(14,4),
        "ActualDryYieldPercent" numeric(14,2),
        "LossPercent" numeric(14,2),
        "InputUnitCost" numeric(14,2) NOT NULL,
        "OutputUnitCost" numeric(14,2),
        "Status" integer NOT NULL,
        "StartedAtUtc" timestamp with time zone NOT NULL,
        "CompletedAtUtc" timestamp with time zone,
        "Notes" text,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_ProcessingBatches" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260831033333_BusinessCmsAndOperations') THEN
    CREATE TABLE cacao."PublicContents" (
        "Id" uuid NOT NULL,
        "ContentKey" character varying(80) NOT NULL,
        "Section" integer NOT NULL,
        "Eyebrow" character varying(120) NOT NULL,
        "Title" character varying(240) NOT NULL,
        "Subtitle" character varying(500) NOT NULL,
        "Body" text NOT NULL,
        "PrimaryCtaLabel" character varying(100),
        "PrimaryCtaUrl" character varying(500),
        "SecondaryCtaLabel" character varying(100),
        "SecondaryCtaUrl" character varying(500),
        "Icon" character varying(80),
        "ImageUrl" character varying(500),
        "DisplayOrder" integer NOT NULL,
        "IsPublished" boolean NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_PublicContents" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260831033333_BusinessCmsAndOperations') THEN
    CREATE TABLE cacao."CashMovements" (
        "Id" uuid NOT NULL,
        "CashRegisterId" uuid NOT NULL,
        "Direction" integer NOT NULL,
        "Category" integer NOT NULL,
        "Amount" numeric(14,2) NOT NULL,
        "Description" character varying(300) NOT NULL,
        "ReferenceId" uuid,
        "ReferenceCode" character varying(80),
        "PaymentMethod" integer NOT NULL,
        "OccurredAtUtc" timestamp with time zone NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_CashMovements" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_CashMovements_CashRegisters_CashRegisterId" FOREIGN KEY ("CashRegisterId") REFERENCES cacao."CashRegisters" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260831033333_BusinessCmsAndOperations') THEN
    CREATE TABLE cacao."InventoryLots" (
        "Id" uuid NOT NULL,
        "Code" text NOT NULL,
        "PurchaseId" uuid,
        "ProcessingBatchId" uuid,
        "Variety" integer NOT NULL,
        "State" integer NOT NULL,
        "InitialQuantityQuintals" numeric(14,4) NOT NULL,
        "AvailableQuantityQuintals" numeric(14,4) NOT NULL,
        "UnitCost" numeric(14,2) NOT NULL,
        "HumidityPercent" numeric(14,2) NOT NULL,
        "Status" integer NOT NULL,
        "ReceivedAtUtc" timestamp with time zone NOT NULL,
        "Notes" text,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_InventoryLots" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_InventoryLots_ProcessingBatches_ProcessingBatchId" FOREIGN KEY ("ProcessingBatchId") REFERENCES cacao."ProcessingBatches" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_InventoryLots_Purchases_PurchaseId" FOREIGN KEY ("PurchaseId") REFERENCES cacao."Purchases" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260831033333_BusinessCmsAndOperations') THEN
    CREATE TABLE cacao."ProcessingLotAllocations" (
        "Id" uuid NOT NULL,
        "ProcessingBatchId" uuid NOT NULL,
        "InventoryLotId" uuid NOT NULL,
        "QuantityQuintals" numeric(14,4) NOT NULL,
        "UnitCost" numeric(14,2) NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_ProcessingLotAllocations" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ProcessingLotAllocations_InventoryLots_InventoryLotId" FOREIGN KEY ("InventoryLotId") REFERENCES cacao."InventoryLots" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_ProcessingLotAllocations_ProcessingBatches_ProcessingBatchId" FOREIGN KEY ("ProcessingBatchId") REFERENCES cacao."ProcessingBatches" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260831033333_BusinessCmsAndOperations') THEN
    CREATE TABLE cacao."SaleLotAllocations" (
        "Id" uuid NOT NULL,
        "SaleId" uuid NOT NULL,
        "InventoryLotId" uuid NOT NULL,
        "QuantityQuintals" numeric(14,4) NOT NULL,
        "UnitCost" numeric(14,2) NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_SaleLotAllocations" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SaleLotAllocations_InventoryLots_InventoryLotId" FOREIGN KEY ("InventoryLotId") REFERENCES cacao."InventoryLots" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_SaleLotAllocations_Sales_SaleId" FOREIGN KEY ("SaleId") REFERENCES cacao."Sales" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260831033333_BusinessCmsAndOperations') THEN
    CREATE INDEX "IX_CashMovements_CashRegisterId" ON cacao."CashMovements" ("CashRegisterId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260831033333_BusinessCmsAndOperations') THEN
    CREATE INDEX "IX_CashMovements_OccurredAtUtc" ON cacao."CashMovements" ("OccurredAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260831033333_BusinessCmsAndOperations') THEN
    CREATE UNIQUE INDEX "IX_CashRegisters_BusinessDate" ON cacao."CashRegisters" ("BusinessDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260831033333_BusinessCmsAndOperations') THEN
    CREATE UNIQUE INDEX "IX_InventoryLots_Code" ON cacao."InventoryLots" ("Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260831033333_BusinessCmsAndOperations') THEN
    CREATE INDEX "IX_InventoryLots_ProcessingBatchId" ON cacao."InventoryLots" ("ProcessingBatchId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260831033333_BusinessCmsAndOperations') THEN
    CREATE INDEX "IX_InventoryLots_PurchaseId" ON cacao."InventoryLots" ("PurchaseId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260831033333_BusinessCmsAndOperations') THEN
    CREATE INDEX "IX_InventoryLots_Variety_State_Status_ReceivedAtUtc" ON cacao."InventoryLots" ("Variety", "State", "Status", "ReceivedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260831033333_BusinessCmsAndOperations') THEN
    CREATE UNIQUE INDEX "IX_ProcessingBatches_Code" ON cacao."ProcessingBatches" ("Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260831033333_BusinessCmsAndOperations') THEN
    CREATE INDEX "IX_ProcessingBatches_Status_StartedAtUtc" ON cacao."ProcessingBatches" ("Status", "StartedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260831033333_BusinessCmsAndOperations') THEN
    CREATE INDEX "IX_ProcessingLotAllocations_InventoryLotId" ON cacao."ProcessingLotAllocations" ("InventoryLotId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260831033333_BusinessCmsAndOperations') THEN
    CREATE UNIQUE INDEX "IX_ProcessingLotAllocations_ProcessingBatchId_InventoryLotId" ON cacao."ProcessingLotAllocations" ("ProcessingBatchId", "InventoryLotId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260831033333_BusinessCmsAndOperations') THEN
    CREATE UNIQUE INDEX "IX_PublicContents_ContentKey" ON cacao."PublicContents" ("ContentKey");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260831033333_BusinessCmsAndOperations') THEN
    CREATE INDEX "IX_PublicContents_Section_DisplayOrder" ON cacao."PublicContents" ("Section", "DisplayOrder");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260831033333_BusinessCmsAndOperations') THEN
    CREATE INDEX "IX_SaleLotAllocations_InventoryLotId" ON cacao."SaleLotAllocations" ("InventoryLotId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260831033333_BusinessCmsAndOperations') THEN
    CREATE UNIQUE INDEX "IX_SaleLotAllocations_SaleId_InventoryLotId" ON cacao."SaleLotAllocations" ("SaleId", "InventoryLotId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260831033333_BusinessCmsAndOperations') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260831033333_BusinessCmsAndOperations', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260831050242_GlobalContactSmtpAndReceipts') THEN
    ALTER TABLE cacao."Sales" ADD "CustomerEmail" character varying(180);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260831050242_GlobalContactSmtpAndReceipts') THEN
    ALTER TABLE cacao."Producers" ADD "Email" character varying(180);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260831050242_GlobalContactSmtpAndReceipts') THEN
    ALTER TABLE cacao."BusinessSettings" ADD "ContactAddress" character varying(400) NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260831050242_GlobalContactSmtpAndReceipts') THEN
    ALTER TABLE cacao."BusinessSettings" ADD "ContactEmail" character varying(180) NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260831050242_GlobalContactSmtpAndReceipts') THEN
    ALTER TABLE cacao."BusinessSettings" ADD "ContactPhone" character varying(40) NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260831050242_GlobalContactSmtpAndReceipts') THEN
    ALTER TABLE cacao."BusinessSettings" ADD "EmailSendingEnabled" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260831050242_GlobalContactSmtpAndReceipts') THEN
    ALTER TABLE cacao."BusinessSettings" ADD "GoogleMapsEmbedUrl" character varying(1200) NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260831050242_GlobalContactSmtpAndReceipts') THEN
    ALTER TABLE cacao."BusinessSettings" ADD "SmtpEmail" character varying(180) NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260831050242_GlobalContactSmtpAndReceipts') THEN
    ALTER TABLE cacao."BusinessSettings" ADD "SmtpHost" character varying(240) NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260831050242_GlobalContactSmtpAndReceipts') THEN
    ALTER TABLE cacao."BusinessSettings" ADD "SmtpPassword" character varying(1000) NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260831050242_GlobalContactSmtpAndReceipts') THEN
    ALTER TABLE cacao."BusinessSettings" ADD "SmtpPort" integer NOT NULL DEFAULT 587;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260831050242_GlobalContactSmtpAndReceipts') THEN
    ALTER TABLE cacao."BusinessSettings" ADD "SmtpUseSsl" boolean NOT NULL DEFAULT TRUE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260831050242_GlobalContactSmtpAndReceipts') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260831050242_GlobalContactSmtpAndReceipts', '8.0.11');
    END IF;
END $EF$;
COMMIT;

